name: Add a new mod
description: Register a new mod in the catalog
title: "[Mod]: "
labels: ["triage"]
projects: []
assignees: []
body:
  - type: input
    id: mod_id
    attributes:
      label: Mod ID
      description: What is the mod ID of your mod
      placeholder: test_mod
    validations:
      required: true
  - type: input
    id: repo_url
    attributes:
      label: Repository URL
      description: What is the URL of the repository of your mod
      placeholder: https://github.com/balamod/mods
    validations:
      required: true
  - type: dropdown
    id: release_method
    attributes:
      label: Release Method
      options:
        - label: GitHub Releases
        - label: Branch Tarball
      default: 0
    validations:
      required: true
